### ISSUE TITLE
Link title doesn't handle `cf` links

### ISSUE THREAD

**Issue by srid** [ihsanturk/neuron.vim#13]
`<abcdefg>` works (it displays the title aside), but not `<abcdefg?cf>`.

**Comment by ihsanturk** [comment]
Is it okay to change the current regex for zettel links 
`<\([0-9a-zA-Z_-]\+\)>`
to optional cf one 
`<\([0-9a-zA-Z_-]\+\(?cf\)\?\)>`?
If there are other special keywords we need to add those like this: `<\([0-9a-zA-Z_-]\+\(?cf\|?another\)\?\)>`

**Comment by srid** [comment]
Here's what neuron allows:

https://github.com/srid/neuron/blob/c0a52a2ad9e01e061815c856661e71f4a0cd5688/neuron/src/lib/Neuron/Markdown.hs#L205

**Comment by srid** [comment]
@ihsanturk In practice including `?cf` to your current regex will be sufficient I think.

In theory, neuron links can be one of several types (link ID being one of them, but you also have `z:zettels` and `z:tags`). The full parser is [here](https://github.com/srid/neuron/blob/c0a52a2ad9e01e061815c856661e71f4a0cd5688/neuron/src/lib/Neuron/Zettelkasten/Query/Parser.hs#L40-L41).

**Comment by ihsanturk** [comment]
I've didn't quite understand where the other type of links redirect. Is it redirects to a zettel list. If so, how can we add virtual titles to multiple zettels?
How can I test this other type of links?
