### ISSUE TITLE
Link title appears at the end of line instead of next to link

### ISSUE THREAD

**Issue by srid** [ihsanturk/neuron.vim#14]
![image](https://user-images.githubusercontent.com/3998/85809147-f24c1700-b724-11ea-8da5-6fc6d7b5f96b.png)

^ I would expect the title to appear right after the link, but it appears at the very end of the line, which could be a bit confusing.

**Comment by ihsanturk** [comment]
I found this in `:help nvim_buf_set_virtual_text` I think that is not possible with our approach.
![help-for-nvim-buf-set-virtual-text](https://user-images.githubusercontent.com/24369769/85859861-80c4a500-b7c6-11ea-8f09-63ce603b38cc.png)

**Comment by srid** [comment]
Looks like we would need https://github.com/neovim/neovim/pull/11745

**Comment by ihsanturk** [comment]
That's awesome. I wish I can help developing the https://github.com/neovim/neovim to make it faster.

**Comment by ihsanturk** [comment]
Closing this for now. We can open again when the feature merged to neovim.
