### ISSUE TITLE
Use correct directory

### ISSUE THREAD

**Issue by Nadrieril** [ihsanturk/neuron.vim#19]
`neuron#refresh_cache` runs `neuron query --uri 'z:zettels'`. This however uses the default zettelkasten directory. The correct commant is `neuron -d path/to/zettelkasten query --uri 'z:zettels'` to work with a user-specified zettelkasten path.

**Comment by Nadrieril** [comment]
Also is would be nice if the plugin caught neuron errors and displayed them to the user. Right now I get an illegible parse error that seems to originate from `util#is_zettelid_valid` when in fact it comes from the `json_decode` call on an empty input. Same for `jq` errors.

**Comment by ihsanturk** [comment]
> Also is would be nice if the plugin caught neuron errors and displayed them to the user. 

@Nadrieril, I've did not add this yet. Should we `echo` the error directly from `system()` function output if an error happens while calling a neuron command?

**Comment by Nadrieril** [comment]
Yeah that would be nice
