### ISSUE TITLE
Failure with latest `neuron`

### ISSUE THREAD

**Issue by Nadrieril** [ihsanturk/neuron.vim#20]
Latest `neuron` has changed the json output format. Instead of looking like `zettelID`, the keys now look like `id`. This breaks the jq processing and various other things.

**Comment by srid** [comment]
Wasn't this already fixed in #17?

**Comment by Nadrieril** [comment]
I am very confused. I was pretty sure neuron used `zettelID` a long time ago. Then I updated neuron and the output changed to `id`. How come #17 says it's gone the other way around? Also I just pulled neuron master and it uses `id`.

**Comment by Nadrieril** [comment]
Ah, lorri had hidden a build failure so I hadn't actually got the latest neuron. Too bad, I really liked the shorter keys :(
