### ISSUE TITLE
Error when editing new zettel

### ISSUE THREAD

**Issue by Nadrieril** [ihsanturk/neuron.vim#21]
If I run `nvim foo.md` where `foo` doesn't yet exist, I get:
```
Error detected while processing function <SNR>49_set_filetype[5]..<SNR>49_add_virtual_titles:                                                      
line    9:                                                                                                                                         
E484: Can't open file /.../zettelkasten/foo.md 
```
I don't think the plugin should be reading the current file from disk; shouldn't it be reading from the opened buffer instead? This is probably linked to the fact that virtual titles don't update unless I reload the file, but that's too bad too: they could be updated live or at least on save.

**Comment by ihsanturk** [comment]
Related to #12.

**Comment by Nadrieril** [comment]
#12 is different, because solving #12 would mean not using only neuron to generate the cache.
This issue is much easier: I don't see a good reason to read the currently open file from disk since the contents are already in the current buffer. In fact it's deeper than that: a vim plugin like that _should_ only operate on buffers, never on underlying files. You wouldn't expect a syntax highlighting plugin to crash before you save the file the first time.

**Comment by ihsanturk** [comment]
I see. We should do this right?
```diff
-for line in readfile(expand("%:p"))
+for line in getbufline(bufname('%'), 1, "$")
```

**Comment by Nadrieril** [comment]
I'm not very familiar with vimscript but that looks right yeah!
