### ISSUE TITLE
Display title of the linked zettel inline

### ISSUE THREAD

**Issue by srid** [ihsanturk/neuron.vim#3]
I wonder if this is actually possible in Vim. The [emacs mode](https://github.com/felko/neuron-mode#neuron-mode) implements it. Neovim has something called 'virtual text' ([here's a demo](https://asciinema.org/a/236226)).

**Comment by ihsanturk** [comment]
I was thinking about concealing normal text but that virtual text thing would be awesome. I didn't know that and I will try to implement soon.
