### ISSUE TITLE
Documentation improvements needed : basic usage

### ISSUE THREAD

**Issue by gamecubate** [ihsanturk/neuron.vim#31]
I am trying out neuron.vim with neovim and have configured init.vim.

I presume that Default Mappings are there by... default. Thus no configuration is needed for those. Yet, in normal mode (using neovim v0.4.3), `ESC :gzn` displays a `E492: not an editor command: gzn` error. Or, still in normal mode, just pressing `gzn` displays a `E486: Pattern not found: file` message. What am I doing wrong?

A session recording (w. asciinema?) would be very useful.

Thanks!

**Comment by Widdershin** [comment]
Does the default zettelkasten directory exist? I think I ran into that as well before creating that directory.

You can see the default by running `neuron --help`. After that it should work as expected, at least it has for me.

**Comment by gamecubate** [comment]
`Does the default zettelkasten directory exist?`

It didn't. I have now created it but the problem persists.

I am not very familiar with (neo)vim and perhaps this is due to some incorrect usage on my part.

Thanks again.

**Comment by ihsanturk** [comment]
`:gzn` is not the way to open a new zettel, it is `gzn in normal mode`. And the error that you are getting `E486: Pattern not found: file` is becoming from neuron, I think. When you `hit gzn`, the plugin `triggers the neuron#edit_zettel_new() function` and it will run `neuron new 'PLACEHOLDER'` command and I guess that is the problem, neuron can't create the file and this plugin tries to open a file that could not be created. 

Can you run this command manually in your terminal to see if the error arises from `neuron`:
```sh
neuron new 'TEST'; echo $?
```
Do you get a file path or an error?

Do not forget to delete the TEST file (you will get the filepath if no errors happen.)

**Comment by TanayB11** [comment]
While I agree there should be more documentation on the repo itself, you can run `:help neuron.vim` in vim to get an idea of the basic usage.

**Comment by gamecubate** [comment]
That doesn't work either: `E149: Sorry, no help for neuron.vim `.

**Comment by TanayB11** [comment]
It looks like the basics are just on the repo's README anyway, if that helps.

**Comment by gamecubate** [comment]
I've been through that README more times than I'd care to say.

**Comment by gamecubate** [comment]
So, to recap:
- `$ neuron new 'TEST'; echo $?` works
- `gzn` reports a `E486: Pattern not found: BAT` error
- `:help neuron.vim` reports a `E149: Sorry, no help for neuron.vim` error.

Something's definitely afoot. :)

**Comment by Widdershin** [comment]
@gamecubate what operating system are you running?

**Comment by gamecubate** [comment]
@Widdershin macOS (High Sierra 10.13.6)

**Comment by ihsanturk** [comment]
### Plugin did not installed or sourced.

When I open a vim instance that has not got this plugin I get the same errors that you get. 

I think you do not have or not sourced this plugin. I think you (or something else) did something wrong with the installation in your init.vim.

By default `gz` is not mapped to anything. So we can assume you are only pressing `n`. And that is used for jump to next searched thing. So you do not have the plugin and searching for the thing you last searched and it seems like it can't find "BAT" then it pops an error "E486: Pattern not found: BAT"

My suggestion is reinstall the plugin again or please describe your installation method.

**Comment by gamecubate** [comment]
@ihsanturk  You are right about the error being related to the last search term.

So, I double-checked the installation instructions of your README. Nothing seems out of place. If you have time, let me know if you can spot the error. Thanks!

**~/.config/nvim/init.vim :**
```
" vim-plug init
call plug#begin(stdpath('data') . '/plugged')

" gruvbox theme
Plug 'morhetz/gruvbox'

" neuron and friends
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'BurntSushi/ripgrep'
Plug 'ihsanturk/neuron.vim'
call plug#end()

" activate gruvbox theme
" per https://github.com/morhetz/gruvbox/wiki/Installation
autocmd vimenter * colorscheme gruvbox
```

**Comment by Widdershin** [comment]
Did you source your `init.vim` and run `:PlugInstall`?

```
:so $MYVIMRC
:PlugInstall
```

**Comment by gamecubate** [comment]
That was it!

I hadn't seen these instructions in the neovim manual (after a glance-through).

Thanks @Widdershin ! Much appreciated.
