### ISSUE TITLE
Create a nix package

### ISSUE THREAD

**Issue by ihsanturk** [ihsanturk/neuron.vim#4]

**Comment by i077** [comment]
I used the nixpkgs [documentation](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/vim.section.md) to make a new PR that adds this plugin at NixOS/nixpkgs#90427.

**Comment by i077** [comment]
Commenting here to say that the PR was just merged! Should be landing in nixos-unstable soon.
