### ISSUE TITLE
what is best way to migrate to neuron?

### ISSUE THREAD

**Issue by babygau** [ihsanturk/neuron.vim#45]
i'm wondering if there is better way to change my current note filename into `random id format` as recommended by `neuron`? and this `id` should be understandable by `neuron`

**Comment by srid** [comment]
You can use this command to create a random ID, in the same format generated by `neuron new`:

```
head /dev/urandom | tr -dc a-z0-9 | head -c 8
```

If you have say, `foo.md`, you can rename it in the command line as:

```
mv foo.md $(head /dev/urandom | tr -dc a-z0-9 | head -c 8).md
```

**Comment by babygau** [comment]
tks u, i did it 👍❤️
