### ISSUE TITLE
Read title from H1 by default

### ISSUE THREAD

**Issue by i077** [ihsanturk/neuron.vim#5]
Neuron now puts a new title in a heading 1 by default rather than the YAML block as of srid/neuron@024996b, so there are now two places where the title could be.

**Comment by ihsanturk** [comment]
Okay I'm working on it. Thanks for reporting. 👍 
But there is a problem for me about git branches: I am trying to add a different feature in `dev` branch. How should I stop (but don't loose) that work and fix just the title problem that you mentioned? Should I just derive another branch (`read title properly`)  from `master` and fix the issue in that branch? But in that case, I would also need to update (merge) the `dev` branch without loosing the uncommited changes. Or should we copy my `dev` changes to a temp directory and paste back after fixing this title issue? Sorry to bother if irrelevant.

**Comment by i077** [comment]
What branching model are you going after? It seems to me that you're roughly modeling [git-flow](https://jeffkreeftmeijer.com/git-flow/)? In that case, I'd make a new feature branch off of the `dev` branch called `h1_title` or something like that to work on this feature specifically, then merge it back to `dev` when it's ready.

Then when everything is stable, merge `dev` into `master`.

**Comment by srid** [comment]
If you use `neuron query`'s JSON to get zettel metadata, it will already contain the correct title. There should not be any need to parse the zettels yourself (which is what neuron does).

**Comment by ihsanturk** [comment]
Thank you for suggestion @i077 I will try to create another branch off of the `dev`. 

And thank you @srid, I am aware of it and currently trying to implement `neuron query` functions in viml. But there are issues with integrating [fzf.vim](https://github.com/junegunn/fzf.vim), nevertheless, I'm pushing to use neuron's query method and caching that json, anyway integrating with fzf is a different issue.

**Comment by ihsanturk** [comment]
I think with 2086320c9655b01e1c4c292d9e311f2ba68d9a2b commit fixed this. So I'm closing this. If anything unexpected happens feel free to reopen. Thanks again.
