### ISSUE TITLE
edit_zettel_new conflicts with title IDs on neuron 1.0.0.0

### ISSUE THREAD

**Issue by pauljxtan** [ihsanturk/neuron.vim#50]
It seems that `edit_zettel_new` doesn't play nicely with the new [title ID](https://github.com/srid/neuron/issues/408) feature introduced in neuron 1.0.0.0, since the zettel created by `neuron new` is now named "PLACEHOLDER" instead of a random ID.

Also, it seems that the `# PLACEHOLDER` title is no longer written to the buffer, causing `search("PLACEHOLDER")` to fail and the first line to be deleted instead.

https://github.com/ihsanturk/neuron.vim/blob/07521a3ef2940bd726e7b4d50b82e46898e686cc/autoload/neuron.vim#L60-L61

I understand that https://github.com/ihsanturk/neuron.vim/issues/12 is related, but not quite the same issue. Please do close this if I'm mistaken.

(Thanks for the awesome plugin, by the way :+1:)

**Comment by fiatjaf** [comment]
So neuron new doesn't assign a random id to the new zettel anymore? This is terrible. We'll have to come up with a solution to do random ids again!

**Comment by pauljxtan** [comment]
> So neuron new doesn't assign a random id to the new zettel anymore? This is terrible. We'll have to come up with a solution to do random ids again!

Technically it is able to, but just not when using the "PLACEHOLDER" title. That is, `neuron new` by itself does generate a random ID.

So I think the simplest solution might be to just not use a title at all, but I'm unsure of what the original rationale was for using the placeholder in the first place, so maybe that's not a good idea?

**Comment by srid** [comment]
Are you using [this fork](https://github.com/fiatjaf/neuron.vim) (which is maintained) as recommended in [the docs](https://neuron.zettel.page/editor.html)?

`neuron new` doesn't add a title anymore--that's a good thing, esp. with title IDs (from which title is inferred). All it injects in the created note is the `date` metadata field.

**Comment by srid** [comment]
Also https://github.com/felko/neuron-mode/pull/64#issuecomment-704273334

**Comment by pauljxtan** [comment]
Ah, I was not aware of that fork - thanks for pointing that out! Honestly I'd still been on neuron 0.4 until yesterday, and only just upgraded, so clearly I'm a bit behind the times :smiley:

**Comment by fiatjaf** [comment]
Oh, sorry. My comments here make no sense. Also I'll put up a fix on my fork.

**Comment by pauljxtan** [comment]
Cheers guys. Closing this now.
