### ISSUE TITLE
Search existing zettels via title only

### ISSUE THREAD

**Issue by Morgawr** [ihsanturk/neuron.vim#51]
I'm not sure if I missed this, but using gzs (EditZettelSearchContent) works great but performs a search on all existing zettel content. Sometimes I just want to open a certain note and I'd like to just search/match the title of it, and not the content of my whole zettelkasten when I try to find it.

It would be nice to have a way to limit the search matching query to just the titles.

**Comment by fiatjaf** [comment]
`gzi` will do that and insert the selected zettel.
`gzz` will do that and open the selected zettel for editing.

**Comment by Morgawr** [comment]
Oh, looks like gzz is the command I had missed. Sounds like it's already working as intended then, apologies for the spam and thanks for the help!
