### ISSUE TITLE
Archive this repo? Update readme to point people to active repo

### ISSUE THREAD

**Issue by fenetikm** [ihsanturk/neuron.vim#52]
Since the development is now going on in https://github.com/fiatjaf/neuron.vim/ I am wondering if it would be a good idea to archive this repo or at least just update the README to help people work out where to go to post issues?

Cheers.

**Comment by ihsanturk** [comment]
I have some plans to maintain this repo but a bit busy these days. But I am adding a note to that fork for now.

**Comment by fenetikm** [comment]
Great - thanks 👍
