### ISSUE TITLE
Add [[]] wiki link support

### ISSUE THREAD

**Issue by NullSense** [ihsanturk/neuron.vim#6]
https://github.com/srid/neuron/pull/237 support is getting added for neuron.

**Comment by srid** [comment]
This is not an official feature of neuron, it may not be supported going forward. Users should not normally use it. See https://github.com/srid/neuron/issues/241

**Comment by srid** [comment]
In other words, don't implement this.

**Comment by jrekier** [comment]
This issue should be reopened as the newest installment of neuron seems to now use [[id]] in place of <id>

**Comment by srid** [comment]
Syntax is documented here: https://neuron.zettel.page/2011504.html

Basically `<...>` is deprecated (still supported) in favour of the new default: `[[...]]` as well as `[[[...]]]`.

**Comment by jrekier** [comment]
[relevant place to change is here](https://github.com/ihsanturk/neuron.vim/blob/07521a3ef2940bd726e7b4d50b82e46898e686cc/autoload/util.vim#L78-L92). But I can't get it to work on my own :(
